DPE-2311 Z-Index konsolidieren
mumprod/hr-design-system-handlebars pull request #664
Opened 2023-06-29 13:24 UTC by Sunny1112358

Akzeptanzkriterien:

Elemente, die nicht überlagert werden dürfen, sind aufgelistet
Z-Index ist so angepasst, dass keine Fehler entstehen (Hierarchie der Elemente ist korrekt)

2023-07-04 14:53 UTC, szuelch requested changes
Hi @Sunny1112358, 
please change the config values in tailwind.config.js according to what if written in the comment at that file.

Furthermore please only use yarn as the package manager for this project. So instead of npm install or npm ci use yarn install. I changed that when updating to storybook 7. Please also delete the package.lock.json which was generated when running npm install.

2023-07-04 14:53 UTC, szuelch commented on tailwind.config.js
Hey @Sunny1112358 , why do you configure z-110 and z-120 with a z-index value of 150 and 160. Please use 110 for z-110 and 120 for z-120.

2023-07-04 14:58 UTC, Sunny1112358 commented on tailwind.config.js
yea it was by accident. Thanks for spotting it out

2023-07-04 14:59 UTC, Sunny1112358 commented on tailwind.config.js
I've been using yarn as well. I'll remove the package lock.

2023-07-26 09:51 UTC, szuelch approved these changes

2023-07-26 10:24 UTC, merged